member_hobbies={
        '松田':{'SNS','麻雀','自転車'},
        '麻木':{'麻雀','食べ歩き','数学','数学','数学',},
}
#全員の趣味一覧を表示
print(member_hobbies)
#松田君の趣味一覧を表示
print(member_hobbies['松田'])
#麻木さんの趣味一覧を表示
print(member_hobbies['麻木'])
